oauth_client/config/routes.rb
OauthClient::Application.routes.draw do
  match '/auth/:provider/callback', to: 'sessions#create'
  match '/signout', to: 'sessions#destroy', as: 'signout'

  resources :tasks
  root to: 'tasks#index'
end

oauth_client/app/models/user.rb
class User < ActiveRecord::Base
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
    end
  end
end

oauth_client/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from OAuth2::Error do |exception|
    if exception.response.status == 401
      session[:user_id] = nil
      session[:access_token] = nil
      redirect_to root_url, alert: "Access token expired, try signing in again."
    end
  end

private

  def oauth_client
    @oauth_client ||= OAuth2::Client.new(ENV["OAUTH_ID"], ENV["OAUTH_SECRET"], site: "http://localhost:3000")
  end

  def access_token
    if session[:access_token]
      @access_token ||= OAuth2::AccessToken.new(oauth_client, session[:access_token])
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

oauth_client/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    session[:access_token] = auth["credentials"]["token"]
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    session[:access_token] = nil
    redirect_to root_url
  end
end

oauth_client/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = access_token.get("/api/tasks").parsed if access_token
  end

  def create
    access_token.post("/api/tasks", params: {task: {name: params[:name]}})
    redirect_to root_url
  end
end

oauth_client/app/helpers/application_helper.rb
module ApplicationHelper
end

oauth_client/app/helpers/sessions_helper.rb
module SessionsHelper
end

oauth_client/app/helpers/tasks_helper.rb
module TasksHelper
end

oauth_client/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>To Do List</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

oauth_client/app/views/tasks/index.html.erb
<h1>To Do List</h1>

<% if current_user %>
  <%= form_tag tasks_path do %>
    <%= text_field_tag :name %>
    <%= submit_tag "Add" %>
  <% end %>

  <ul id="tasks">
  <% @tasks.each do |task| %>
    <li><%= task["name"] %></li>
  <% end %>
  </ul>

  <p id="logged_in">
    Logged in as <strong><%= current_user.name %></strong>.
    <%= link_to "Sign Out", signout_path %>
  </p>
<% else %>
  <p><strong>Currently not signed in.</strong></p>
  <p>
    <%= link_to "Sign in through To Do List", "/auth/todo" %>
  </p>
<% end %>